// This file was generated by Prisma and updated for Next.js .env.local convention.
import path from "path";
import * as dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js stores secrets in .env.local; load it explicitly for Prisma CLI.
dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"] as string,
  },
});
