export const STOCK_MOVEMENT_REASONS = [
  'FOUND',
  'DAMAGED',
  'STOLEN',
  'DATA_ERROR',
  'RETURNED_TO_SUPPLIER',
  'INITIAL_STOCK',
  'SALE_RETURN',
  'PURCHASE_RECEIVED',
  'STOCK_TAKE_ADJUSTMENT',
  'SALE',
  'VOID_REVERSAL',
] as const;

export type StockMovementReasonValue = (typeof STOCK_MOVEMENT_REASONS)[number];

export const STOCK_MOVEMENT_REASON: Record<
  StockMovementReasonValue,
  StockMovementReasonValue
> = {
  FOUND: 'FOUND',
  DAMAGED: 'DAMAGED',
  STOLEN: 'STOLEN',
  DATA_ERROR: 'DATA_ERROR',
  RETURNED_TO_SUPPLIER: 'RETURNED_TO_SUPPLIER',
  INITIAL_STOCK: 'INITIAL_STOCK',
  SALE_RETURN: 'SALE_RETURN',
  PURCHASE_RECEIVED: 'PURCHASE_RECEIVED',
  STOCK_TAKE_ADJUSTMENT: 'STOCK_TAKE_ADJUSTMENT',
  SALE: 'SALE',
  VOID_REVERSAL: 'VOID_REVERSAL',
};